trajectory: 
  data: 
    path: lm_act_eval/.cache/five-star-trajectories/csv/data+gptv-eligible.csv
    columns:
      y: ground_truth
      y_': GPTV_generations
    extract_fs:
      USER_QUERY:
        QUERY: parse_completion.parse_query
      GOAL:
        chat_completion_messages: parse_completion.parse_content
      action:
        action: extract_action
      thought:
        thought: extract_thought
      explanation:
        explanation: extract_explanation
    logging:
      # log as table by default
      project: opentable
      result: lm_act_eval-run
      hugging:
        space: multion-agi

  comparator:
    gptv:
      model: gpt-4-vision-preview
      max_token: 300
      img_fidelity: high
  
  metrics:
    gptv:
      - GOAL
      - QUERY
    edit_distance:
      - actions
    last_state:
      - URL
    bleu:
      - explanation
      
    llm_relevancy:
      - explanation