trajectory: 
  data: 
    path: lm_act_eval/.cache/five-star-trajectories/csv/data+gptv.csv
    columns:
      y: ground_truth
      y_': GPTV_generations
      extract_fs:
        QUERY:
          - user_inputs: parse_query
        GOAL:
          - chat_completions: parse_content
      - action: extract_action
      - thought: extract_thought
      - explanation: extract_explanation
    logging:
      wandb: 
        project: opentable
        # log as table by default
        result: lm_act_eval-run
      hugging:
        space: multion-agi

  comparator:
    gptv:
      model: gpt-4-vision-preview
      max_token: 300
      img_fidelity: high
  
  metrics:
    gptv:
      - GOAL
      - QUERY
    edit_distance:
      - actions
    last_state:
      - URL
    bleu:
      - explanation
      
    llm_relevancy:
      - explanation