trajectory: 
  data: 
    path: lm_act_eval/.cache/five-star-trajectories/csv/data.csv
    columns:
      trajectory_id: session_id
      action_idx: idx_in_session
      y: ground_truth
      y_': GPTV_generations
    extract_fs:
      # target field:
        # src field
      QUERY:
        QUERY:
      screenshot:
        screenshot:
      GOAL:
        chat_completion_messages: parse_completion.parse_content
      # multiple field, target field used as prefix named '<tgt_field>_<src_field1>'
      HTML:
        DOM: opentable_extract_reservation_details
    logging:
      # log as table by default
      wandb:
        project: opentable
        result: lm_act_eval-run
      braintrust:
        project: multion_opentable

  # benchmark:
  #   gpt-v:
  #     model: gpt-4-vision-preview
  #     max_token: 300
  #     img_fidelity: high
  
  metrics:
      # any fields starting with the same starting string (or match)
    opentable_html:
      # only evaluate last idx of the group
      evaluate_group_last: action_idx
      inputs:
        - HTML
      column_pairs:
        - restaurant_name
      args:
        -
    gpt-v:
      inputs:
        - GOAL
        - QUERY
        - screenshots
      args:
        - PROMPT_VERSION: multion_trajectory
    contextual_precision:
      inputs:
        - inputs: GOAL
        - actual_output: y_
        - expected_output: y
        - retrieval_context: 
      args:
        - threshold: 0.7
        - model: gpt-4
        - include_reason: true
    # edit_distance:
    #   - actions
    # last_state:
    #   - URL
    # bleu:
    #   - explanation
    # llm_relevancy:
    #   - explanation