defaults:
  - base
  # Adjust this part to dynamically create the path based on 'dataset' and 'type' fields
  - dataset@eval_conf: ${dataset}/${type}/dataset
  - metrics@eval_conf: ${dataset}/${type}/metrics
  - comparator@eval_conf: ${dataset}/${type}/comparator


  
format: csv
dataset: opentable
type: trajectory